apiVersion: v1
kind: Service
metadata:
  name: devcalc-redirect-service
spec:
  selector:
    app: devcalc
  type: LoadBalancer
  ports:
    - name: http-redirect
      port: 80
      targetPort: 8080