name: docker-push.yml

on:
  push:
    branches: [ "main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: login Docker HUb
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: config docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build e push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/devcalc-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devcalc-api:${{ github.sha }}

      - name: gerar relatorio actions
        run: |            
            echo "## relatorio de execução" >> $GITHUB_STEP_SUMMARY
            echo "| item | info |" >> $GITHUB_STEP_SUMMARY
            echo "|---|---|" >> $GITHUB_STEP_SUMMARY
            echo "| docker image | ${{ secrets.DOCKERHUB_USERNAME}}/devcalc-api` |" >> $GITHUB_STEP_SUMMARY
            echo "| tag| \`${{ github.sha }}` |" >> $GITHUB_STEP_SUMMARY
            echo "| data| date +'%d/%m/%Y %H:%M:%S' |" >> $GITHUB_STEP_SUMMARY
            echo "| autor| ${{ github.actor }} |" >> $GITHUB_STEP_SUMMARY
            echo "| branch| ${{ github.ref_name }} |" >> $GITHUB_STEP_SUMMARY
          
          
          
